import React from 'react';
import style from './homeMainBtns.module.css';

export default function HomeMainBtns() {
  return (
    <div className={style.box}>
      <div className={style.shopbg}></div>
      <img
        src="/home-images/mainBtnArea/demo.png"
        alt="demo"
        className={style.demo}
      />
      <img
        src="/home-images/h-walkingCat.png"
        alt="demo"
        className={style.cat}
      />
      <img
        src="/home-images/mainBtnArea/h-road.svg"
        alt="demo"
        className={style.road}
      />
      <img
        src="/home-images/mainBtnArea/road1.svg"
        alt="demo"
        className={style.road1}
      />
      <img
        src="/home-images/mainBtnArea/road2.svg"
        alt="demo"
        className={style.road2}
      />
      <img
        src="/home-images/mainBtnArea/road3.svg"
        alt="demo"
        className={style.road3}
      />
      <img
        src="/home-images/mainBtnArea/road4.svg"
        alt="demo"
        className={style.road4}
      />

      <img
        src="/home-images/mainBtnArea/h-shopbtn.svg"
        alt="demo"
        className={style.shopBtn}
      />
      <img
        src="/home-images/mainBtnArea/h-actbtn.svg"
        alt="demo"
        className={style.actBtn}
      />
      <img
        src="/home-images/mainBtnArea/h-resbtn.svg"
        alt="demo"
        className={style.resBtn}
      />
      <img
        src="/home-images/mainBtnArea/h-forumbtn.svg"
        alt="demo"
        className={style.forumBtn}
      />
      <img
        src="/home-images/trafficLight.png"
        alt="demo"
        className={style.light1}
      />
      <img
        src="/home-images/trafficLight.png"
        alt="demo"
        className={style.light2}
      />
      <img
        src="/home-images/trafficLight.png"
        alt="demo"
        className={style.light3}
      />
      <img
        src="/home-images/mainBtnArea/h-trees1.png"
        alt="demo"
        className={style.trees1}
      />
      <img
        src="/home-images/mainBtnArea/h-tree.png"
        alt="demo"
        className={style.tree}
      />
      <img
        src="/home-images/mainBtnArea/h-dbTree.png"
        alt="demo"
        className={style.dbtree}
      />
      <img
        src="/home-images/mainBtnArea/h-dbTree.png"
        alt="demo"
        className={style.dbtree2}
      />
      <img
        src="/home-images/running-dog.svg"
        alt="demo"
        className={style.dog}
      />
    </div>
  );
}
