import Head from 'next/head';
import { Col, Row } from 'antd';
import HomeShopCard from '@/components/ui/cards/homeShopCard';
import style from '@/styles/home.module.css';
import HomeLayout from '@/components/layout/home-layout';
import HomeMainBtn from '@/components/ui/buttons/homeMainBtn';
// import { Inter } from 'next/font/google'

// const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const shopCardsData = [
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
    {
      img: '/home-images/hsprod1.avif',
      type: '服飾類',
      sale: '399',
      name: '搖!搖! 超級水果～酥脆貓零食-鮭魚',
      price: '599',
    },
  ];
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <main className="container-outer">
          <div className={style.headSection}>
            <img
              src="home-images/h-header-photo.png"
              className={style.gwmphoto}
              alt="gwmphoto"
            />
            <img
              src="home-images/h-title.png"
              className={style.gwmtitle}
              alt="title"
            />
          </div>
        </main>
      </header>

      <HomeMainBtn
        img="/home-images/h-logo.png"
        text="提供寵物餐具"
        outline="styles.outline1"
      />

      <div className="container-outer">
        <Row>
          <Col span={2}></Col>
          <Col span={20}>
            <Row className={style.hSection}>
              <Col className={style.hlCards} xs={24} sm={24} md={14}>
                {shopCardsData.map((p, i) => {
                  const { img, type, sale, name, price } = p;
                  return (
                    <HomeShopCard
                      key={i}
                      img={img}
                      type={type}
                      sale={sale}
                      name={name}
                      price={price}
                    />
                  );
                })}
              </Col>
              <Col className={style.hInfo} xs={24} sm={24} md={10}>
                <article>
                  <p className={style.hstitle}>寵物商城</p>
                  <p className={style.hetitle}>SHOP WITH ME</p>
                  <p className={style.hsubtitle}>
                    毛孩的吃喝玩樂都在寵物商城！ 各大品牌狗貓飼料、用品通通有!
                    毛爸媽安心購買，更別錯過每日特殺活動喔~
                  </p>
                  <p className={style.hp}>
                    探索我們的寵物商城，為您的毛小孩尋找完美的驚喜！我們提供精選的寵物用品，從食品到玩具，應有盡有。{' '}
                  </p>
                  <p className={style.hp}>
                    我們致力於提供最高品質的產品，經過嚴格挑選和測試，讓您的寶貝獲得最好的呵護。購物輕鬆方便，讓您和您的寶貝享受無與倫比的購物體驗！
                  </p>

                  <div className={style.hhashes}>
                    <p className={style.hhash}>飼料</p>
                    <p className={style.hhash}>罐頭</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>玩具</p>
                    <p className={style.hhash}>保健品</p>
                    <p className={style.hhash}>服飾</p>
                    <p className={style.hhash}>戶外用品</p>
                  </div>
                  <button>看更多商品</button>
                </article>
              </Col>
            </Row>
            <Row className={style.hSection}>
              <Col className={style.hInfo} xs={24} sm={24} md={10}>
                <article>
                  <p className={style.hstitle}>寵物活動</p>
                  <p className={style.hetitle}>PLAY WITH ME</p>
                  <p className={style.hsubtitle}>
                    這裡是專為您和您的毛小孩設計的狂歡天地。
                  </p>
                  <p className={style.hp}>
                    我們為您提供多元化的寵物活動，包括遠足、比賽、社交聚會和專題工作坊。與其他寵物愛好者一同分享快樂時光，建立友誼和彼此支持。無論您是狗狗、貓咪還是其他寵物的主人，這裡將是您與您的毛小孩共創美好回憶的地方。加入我們，一同體驗無盡的寵物
                    樂趣！
                  </p>

                  <div className={style.hhashes}>
                    <p className={style.hhash}>狗狗健行趣</p>
                    <p className={style.hhash}>寵物瑜伽</p>
                    <p className={style.hhash}>喵星人的外星派對</p>
                    <p className={style.hhash}>萌寵大對決</p>
                  </div>
                  <button>看更多活動</button>
                </article>
              </Col>
              <Col className={style.hrCards} xs={24} sm={24} md={14}></Col>
            </Row>
            <Row className={style.hSection}>
              <Col className={style.hlCards} xs={24} sm={24} md={14}></Col>
              <Col sxs={24} sm={24} md={10}>
                <article>
                  <p className={style.hstitle}>寵物商城</p>
                  <p className={style.hetitle}>SHOP WITH ME</p>
                  <p className={style.hsubtitle}>
                    毛孩的吃喝玩樂都在寵物商城！ 各大品牌狗貓飼料、用品通通有!
                    毛爸媽安心購買，更別錯過每日特殺活動喔~
                  </p>
                  <p className={style.hp}>
                    探索我們的寵物商城，為您的毛小孩尋找完美的驚喜！我們提供精選的寵物用品，從食品到玩具，應有盡有。{' '}
                  </p>
                  <p className={style.hp}>
                    我們致力於提供最高品質的產品，經過嚴格挑選和測試，讓您的寶貝獲得最好的呵護。購物輕鬆方便，讓您和您的寶貝享受無與倫比的購物體驗！
                  </p>

                  <div className={style.hhashes}>
                    <p className={style.hhash}>飼料</p>
                    <p className={style.hhash}>罐頭</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>玩具</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                  </div>
                  <button>看更多商品</button>
                </article>
              </Col>
            </Row>
            <Row className={style.hSection}>
              <Col className={style.hInfo} xs={24} sm={24} md={10}>
                <article>
                  <p className={style.hstitle}>寵物商城</p>
                  <p className={style.hetitle}>SHOP WITH ME</p>
                  <p className={style.hsubtitle}>
                    毛孩的吃喝玩樂都在寵物商城！ 各大品牌狗貓飼料、用品通通有!
                    毛爸媽安心購買，更別錯過每日特殺活動喔~
                  </p>
                  <p className={style.hp}>
                    探索我們的寵物商城，為您的毛小孩尋找完美的驚喜！我們提供精選的寵物用品，從食品到玩具，應有盡有。{' '}
                  </p>
                  <p className={style.hp}>
                    我們致力於提供最高品質的產品，經過嚴格挑選和測試，讓您的寶貝獲得最好的呵護。購物輕鬆方便，讓您和您的寶貝享受無與倫比的購物體驗！
                  </p>

                  <div className={style.hhashes}>
                    <p className={style.hhash}>飼料</p>
                    <p className={style.hhash}>罐頭</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>玩具</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                    <p className={style.hhash}>零食</p>
                  </div>
                  <button>看更多商品</button>
                </article>
              </Col>
              <Col className={style.hrCards} xs={24} sm={24} md={14}></Col>
            </Row>
            <section className={style.shopSection}>
              <div className={style.hSCards}></div>
            </section>
          </Col>
          <Col span={2}></Col>
        </Row>
      </div>
    </>
  );
}

Home.getLayout = (page) => <HomeLayout>{page}</HomeLayout>;
